### ISSUE TITLE
Bug: rails 7 raises an exception

### ISSUE THREAD

**Issue by fnando** [fnando/rails-env#11]
## Description

Rails changed one of the properties to be frozen.

## How to reproduce

Use this gem with any Rails 7 application.

## What do you expect

It works without raising errors.

## What happened instead

[Describe the actual results]

## Software:

- Gem version: [Add gem version here]
- Ruby version: [Add version here]

## Full backtrace

```text
$ rails s
=> Booting Puma
=> Rails 7.0.0.alpha2 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rails-env-1.0.8/lib/rails-env.rb:69:in `unshift': can't modify frozen Array: ["/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/channels", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/controllers", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/controllers/concerns", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/helpers", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/models", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/models/concerns", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/turbo-rails-0.9.0/app/jobs", "/Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/importmap-rails-0.9.3/app/helpers"] (FrozenError)
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rails-env-1.0.8/lib/rails-env.rb:69:in `propagate_autoload_paths'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rails-env-1.0.8/lib/rails-env.rb:36:in `propagate_configuration!'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rails-env-1.0.8/lib/rails-env.rb:94:in `on'
	from /Users/fnando/Projects/personal/35mm/config/initializers/hosts.rb:3:in `<top (required)>'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:669:in `load'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:669:in `block in load_config_initializer'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications.rb:209:in `instrument'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:668:in `load_config_initializer'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:622:in `block (2 levels) in <class:Engine>'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:621:in `each'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:621:in `block in <class:Engine>'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:32:in `run'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:50:in `each'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:415:in `call'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application.rb:369:in `initialize!'
	from /Users/fnando/Projects/personal/35mm/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command/base.rb:87:in `perform'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command.rb:48:in `invoke'
	from /Users/fnando/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by fnando** [comment]
[This was already fixed](https://github.com/fnando/rails-env/tree/7b37a30ea41b97ef036e78a670dc5f6a02f8eaea), but not released.
